### ISSUE TITLE
Winutil don't install any apps on my W10 20H2 19042.1706 previous versions of debloat work as expected

### ISSUE THREAD

**Issue by mrg9999** [ChrisTitusTech/winutil#15]
@ChrisTitusTech 

GUI opens and can be resized

I invoked it via iwr -useb https://christitus.com/win | iex and direct from PS1 saved from this Git

No apps seems to get installed. Screen briefly flashes and a popop window says  app installed.

Is there some logfile or dependencies?

My PS version
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

![2022-05-15 - winutil sc 01](https://user-images.githubusercontent.com/7822877/168452723-fec5bd94-ab34-4bd6-ba58-133048f50606.jpg)

Previous debloat runs fine - example uninstall onedrive
![2022-05-15 - previous debloat runs fine](https://user-images.githubusercontent.com/7822877/168452755-747d84f6-9f16-4ef4-8414-efb20c6ef736.jpg)

**Comment by adamkagdi** [comment]
Hey, basically I had the same problem too, for me the fix was to run the old script, when the old script is running, it checks and updates winget and stuff, after it is done with that and the menu comes up, you can close that menu and then run the new script, it should work after that.

**Comment by mrg9999** [comment]
> Hey, basically I had the same problem too, for me the fix was to run the old script, when the old script is running, it checks and updates winget and stuff, after it is done with that and the menu comes up, you can close that menu and then run the new script, it should work after that.

My machine doesn't seem to be able to install WINGET. I can use chocolatey fine. 
Is there an easy way to install WINGET standalone?

**Comment by Carterpersall** [comment]
@mrg9999 what edition of Windows do you run?

**Comment by mrg9999** [comment]
Windows 10 X64 Professional Version
10.0.19042
20H2 Build (19042.1706)

![Q551W10](https://user-images.githubusercontent.com/7822877/168499525-73b531ea-5da2-4598-b97d-e878013b9d2b.jpg)

**Comment by adamkagdi** [comment]
> > Hey, basically I had the same problem too, for me the fix was to run the old script, when the old script is running, it checks and updates winget and stuff, after it is done with that and the menu comes up, you can close that menu and then run the new script, it should work after that.
> 
> My machine doesn't seem to be able to install WINGET. I can use chocolatey fine. Is there an easy way to install WINGET standalone?

I highly suggest running the old script first:
`iwr -useb https://git.io/JJ8R4 | iex`

Then this one:
`iwr -useb https://christitus.com/win | iex`

**Comment by Carterpersall** [comment]
Yeah it seems that the issue is that the script lacks the portion that installs winget

Should be fixed in #21

**Comment by mrg9999** [comment]
@Carterpersall 
I tried your change  and it still doesn't work for me.
I don't know much about Powershell So I recorded a error log file below

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Configuration:       Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              American Megatrends Inc. Q551LN.203, 26/06/2014

////
**********************
Windows PowerShell transcript start
Start time: 20220516232249
Username: W10VM751\user-l
RunAs User: W10VM751\user-l
Configuration Name: 
Machine: W10VM751 (Microsoft Windows NT 10.0.19042.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 14504
PSVersion: 5.1.19041.1682
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.1682
BuildVersion: 10.0.19041.1682
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started

Checking if Winget is Installed...
Winget not found, installing it now.
Get-Process : Cannot find a process with the name "AppInstaller". Verify the process name and call the cmdlet again.
At C:\temp\check_winget.ps1:40 char:18
+             $nid = (Get-Process AppInstaller).Id
+                     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AppInstaller:String) [Get-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.GetProcessCommand
Get-Process : Cannot find a process with the name "AppInstaller". Verify the process name and call the cmdlet again.
At C:\temp\check_winget.ps1:40 char:18
+             $nid = (Get-Process AppInstaller).Id
+                     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AppInstaller:String) [Get-Process], ProcessCommandException
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.GetProcessCommand

PS C:\temp> TerminatingError(Wait-Process): "Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again."
Wait-Process : Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide an argument that is 
not null or empty, and then try the command again.
At C:\temp\check_winget.ps1:41 char:27
+             Wait-Process -Id $nid
+                              ~~~~
    + CategoryInfo          : InvalidData: (:) [Wait-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WaitProcessCommand
Wait-Process : Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide an argument that is
not null or empty, and then try the command again.
At C:\temp\check_winget.ps1:41 char:27
+             Wait-Process -Id $nid
+                              ~~~~
    + CategoryInfo          : InvalidData: (:) [Wait-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.WaitProcessCommand

Winget Installed
**********************
Windows PowerShell transcript end
End time: 20220516232255
**********************

////

**Comment by mrg9999** [comment]
Fixed
I had to re-install MS Windows Store (that a previous) Debloat had removed and re-enable telemetary. Upon reboot winget was installed

$ winget -v   
v1.0.11692    

And the script runs as expected.

What it needs IMO is proper checking of these dependencies.

I used a combination of these
Get-AppXPackage -allusers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}


pasted this into 
https://www.microsoft.com/en-us/p/microsoft-store/9wzdncrfjbmp

https://store.rg-adguard.net/

![2022-05-17 - Store links](https://user-images.githubusercontent.com/7822877/168805501-4574cdb4-331b-40cf-9f1e-23705b6bbfb1.jpg)

**Comment by Carterpersall** [comment]
@mrg9999 it seems that your issue was that you were lacking the Desktop App Installer package. It was probably uninstalled in that script as well. I can include a check for that in my pull request as the second install method should work in that situation.

What the command you ran does is reinstall every app that was originally included with Windows, which includes the Microsoft Store and Desktop App Installer, along with the bloatware included with the base install.
