### ISSUE TITLE
Cannot install any packages

### ISSUE THREAD

**Issue by ubrider** [ChrisTitusTech/winutil#1586]
**Describe the bug**
"winget failed to install"

**To Reproduce**
Try install package

**Expected behavior**

**Screenshots**
![image_2024-02-07_122919365](https://github.com/ChrisTitusTech/winutil/assets/9861523/cfb55e3d-cd41-4c93-8aea-750b313ebd93)

**Additional context**

**Comment by Hujgo** [comment]
Same problem here- Fresh Install Windows 11 Pro

**Comment by Yuuh15** [comment]
Same here. This issue needs a lot more attention

**Comment by pirend** [comment]
Same problem here.

Though it was due to my recent "installation" of AtlasOs (https://atlasos.net/) over my current win11...

Winget was reinstalled with winutil previously.

if you need more debug info please let me know. :-)

**Comment by ChrisTitusTech** [comment]
this should now work on fresh win11 installs with broken winget commit f39deab55595aafb73665ea5510ddda569b036a7

**Comment by JorgaWetzel** [comment]
Unfortunately, it still doesn't work.

Checking if Winget is Installed...
Winget v1.6.3482
- Winget up-to-date
Winget Already Installed
===========================================
--      Winget failed to install        ---
===========================================

**Comment by ffonsecaluis** [comment]
still doesn't work., Same problem here- Fresh Install Windows 11 Pro

**Comment by Yuuh15** [comment]
Even github is weird, I tried to clone the repo based on the main branch and it states that the version is from 2024.02.03
![powershell_2O9hmX32cy](https://github.com/ChrisTitusTech/winutil/assets/97139700/992c9512-f80e-407b-934a-66a6e73be1fb)

**Comment by ubrider** [comment]
oof i'm not alone, i forgot to mention it doesn't work on my fresh install of win 11 with latest updates AND Win 10 latest updates too. On my Win10 it worked just days ago and then errors for both.

**Comment by theriverlethe** [comment]
I also had this problem on two successive installs of a Win11 23H2 ISO install. The handy "install winget" button in winutil resolved it, but obviously this is something that should work out of the box.

**Comment by TheVoork** [comment]
![Screenshot 2024-02-07 183122](https://github.com/ChrisTitusTech/winutil/assets/159390047/677bf691-abb6-4eab-b1d5-571a6274bd5f)
Same problems, tried to reinstall winget in config but it did not work. Can't install packages.

**Comment by tekshteint** [comment]
Same problems here as well on windows 11

**Comment by S-Pika** [comment]
Edition	Windows 11 Home
Version	23H2
Installed on	‎2/‎7/‎2024
OS build	22631.3085
Experience  Windows Feature Experience Pack 1000.22684.1000.0

![image](https://github.com/ChrisTitusTech/winutil/assets/109268122/b124f48b-cf22-4cde-8d3d-ca34ccd76da9)

![image](https://github.com/ChrisTitusTech/winutil/assets/109268122/7f2e5de5-b948-4f86-bfea-9711e3ff9866)


ISO was cleaned using this tools MicroWin utility

Also same issue using the "install selected" button, but no issue with the "upgrade all" and "get installed" functions. I have tried to use the reinstall winget option and it re installs winget as shown in the attached log but unlike some people this did not fix the issue.
[choco.summary.log](https://github.com/ChrisTitusTech/winutil/files/14202756/choco.summary.log)
[chocolatey.log](https://github.com/ChrisTitusTech/winutil/files/14202758/chocolatey.log)

**Comment by theriverlethe** [comment]
> ![Screenshot 2024-02-07 183122](https://private-user-images.githubusercontent.com/159390047/303168278-677bf691-abb6-4eab-b1d5-571a6274bd5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNTA1MDEsIm5iZiI6MTcwNzM1MDIwMSwicGF0aCI6Ii8xNTkzOTAwNDcvMzAzMTY4Mjc4LTY3N2JmNjkxLWFiYjYtNGVhYi1iMWQ1LTU3MWE2Mjc0YmQ1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QyMzU2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTQyNzVmNGMyMjZjZDczN2QyZmM1MGYxOTZkZTM1OTU5OTgwZWRhYzlkZDhlY2FmNDkyNDI4MDQwOTIzNGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VocDjXWiq9ogMZw3hpzn9Xq2NlLv4-5lx2N6bbg1i3U) Same problems, tried to reinstall winget in config but it did not work. Can't install packages.

Have you tested it after seeing this error? It looks like chocolatey worked but winget could be throwing a bad error. Winget is working fine on my system but I don't remember seeing this error.

**Comment by ChrisTitusTech** [comment]
reverted to past patch since people were having issues with winget commit c842584cfe2b2368bff57dba281d6715793a682f

**Comment by bca009** [comment]
> reverted to past patch since people were having issues with winget commit c842584cfe2b2368bff57dba281d6715793a682f

Thanks Chris

**Comment by TheVoork** [comment]
I fixed my problem :) I deactivated Windows defender real-time protection in the security dashboard and it did the trick. :P

**Comment by lmartine2000** [comment]
Not working yet.

**Comment by theriverlethe** [comment]
> Not working yet.

What's not working yet? Be specific.

**Comment by bca009** [comment]
Works for me

**Comment by lmartine2000** [comment]
> > Not working yet.
> 
> What's not working yet? Be specific.
Same issue detailed by many people in this tread. Chris posted he had reverted to a patch, and I wrote: Not working yet. 
The Scrips keep failing with these messages:

Winget up-to-date
Winget Already Installed
===========================================
-- Winget failed to install ---
===========================================

Chocolatey v2.2.2
Enabled allowGlobalConfirmation
Checking if Winget is Installed...
Winget not detected
Running Alternative Installer and Direct Installing
Winget Installed

**Comment by ChrisTitusTech** [comment]
> > > Not working yet.
> > 
> > 
> > What's not working yet? Be specific.
> > Same issue detailed by many people in this tread. Chris posted he had reverted to a patch, and I wrote: Not working yet.
> > The Scrips keep failing with these messages:
> 
> # Winget up-to-date
> Winget Already Installed
> # -- Winget failed to install ---
> Chocolatey v2.2.2 Enabled allowGlobalConfirmation Checking if Winget is Installed... Winget not detected Running Alternative Installer and Direct Installing Winget Installed

This is actually a different problem. Clicking Reinstall Winget from Config should get you going.

**Comment by lmartine2000** [comment]
> > > > Not working yet.
> > > 
> > > 
> > > What's not working yet? Be specific.
> > > Same issue detailed by many people in this tread. Chris posted he had reverted to a patch, and I wrote: Not working yet.
> > > The Scrips keep failing with these messages:
> > 
> > 
> > # Winget up-to-date
> > Winget Already Installed
> > # -- Winget failed to install ---
> > Chocolatey v2.2.2 Enabled allowGlobalConfirmation Checking if Winget is Installed... Winget not detected Running Alternative Installer and Direct Installing Winget Installed
> 
> This is actually a different problem. Clicking Reinstall Winget from Config should get you going.

Before posting this issue, I had reinstalled Winget, even went back to a clean windows setup, but the script keeps failing. Now I am testing it on a different PC but no luck.

**Comment by lmartine2000** [comment]
> > > > Not working yet.
> > > 
> > > 
> > > What's not working yet? Be specific.
> > > Same issue detailed by many people in this tread. Chris posted he had reverted to a patch, and I wrote: Not working yet.
> > > The Scrips keep failing with these messages:
> > 
> > 
> > # Winget up-to-date
> > Winget Already Installed
> > # -- Winget failed to install ---
> > Chocolatey v2.2.2 Enabled allowGlobalConfirmation Checking if Winget is Installed... Winget not detected Running Alternative Installer and Direct Installing Winget Installed
> 
> This is actually a different problem. Clicking Reinstall Winget from Config should get you going.

I already had done that before posti g this issue. I had tried many scenaries but no luck. Now I am testing it on a fresh windows setup and it shows same errors.

**Comment by lmartine2000** [comment]
I've found that the script works ok on computers where is had been run before last week. I am running it without problem in my personal laptop where it was setup long time ago. So, it seems  the issue is happening only on fresh installs.

**Comment by Steeloso** [comment]
thx a lot chris, that fixed it

**Comment by Dijkertje92** [comment]
I am still having issues:
"The current system configuration does not support the installation of this package.", is the error message I keep on getting.
![2024-02-08](https://github.com/ChrisTitusTech/winutil/assets/45792489/59b4492c-ed18-45f9-a70b-b4b79ee20e9a)
_Tidal is displayed, but am having issues with Chrome and Teams, too._

I am using a fresh install of Windows 11 23H2
![2024-02-08 (1)](https://github.com/ChrisTitusTech/winutil/assets/45792489/e573218d-48d0-43d9-9be6-d5dd6109712e)

I had this issue since yesterday and came across this thread. I have tried a couple of times using the WinGet Reinstall from the Config tab.
I just now tried using WinGet Reinstall again, but am still receiving the same error as above.

What can I do to resolve this?

**Comment by ubrider** [comment]
Ok it's working again for now on win10.

![image_2024-02-08_204818160](https://github.com/ChrisTitusTech/winutil/assets/9861523/0782a14f-3b47-4629-b4fa-cf834fea8b0a)

**Comment by TheVoork** [comment]
> > ![Screenshot 2024-02-07 183122](https://private-user-images.githubusercontent.com/159390047/303168278-677bf691-abb6-4eab-b1d5-571a6274bd5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNTA1MDEsIm5iZiI6MTcwNzM1MDIwMSwicGF0aCI6Ii8xNTkzOTAwNDcvMzAzMTY4Mjc4LTY3N2JmNjkxLWFiYjYtNGVhYi1iMWQ1LTU3MWE2Mjc0YmQ1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QyMzU2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTQyNzVmNGMyMjZjZDczN2QyZmM1MGYxOTZkZTM1OTU5OTgwZWRhYzlkZDhlY2FmNDkyNDI4MDQwOTIzNGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VocDjXWiq9ogMZw3hpzn9Xq2NlLv4-5lx2N6bbg1i3U) Same problems, tried to reinstall winget in config but it did not work. Can't install packages.
> 
> Have you tested it after seeing this error? It looks like chocolatey worked but winget could be throwing a bad error. Winget is working fine on my system but I don't remember seeing this error.

yes and it worked fine
