### ISSUE TITLE
XboxGipSvc freezes on 'Starting' status

### ISSUE THREAD

**Issue by adolfo-cia** [ChrisTitusTech/winutil#1733]
**Describe the bug**
When running the tweaks (desktop), the service XboxGipSvc is set to manual, but the status remains in 'Starting'.
Windows 11.

**To Reproduce**
1. Run the tweaks (desktop)
2. Go to Windows Services app
3. Look at 'Xbox Accesory Management Service'

**Expected behavior**
The service should in 'Stopped'

**Additional context**
I think the issue is related to the tweaks option 'Disable Telemetry'.
Haven't checked, but a few months ago if you revert the changes, that won't work. Only works if you restore with the system restore point.
Also, I'm not using the Xbox app, but I read other issues in the past that this might break the xbox app.

Thanks for the tool!

**Comment by YusufKhalifadev** [comment]
@adolfo-cia 
It should be fixed now with #1766 
Could you close the issue

**Comment by adolfo-cia** [comment]
@YusufKhalifadev I'm closing the issue but I've not checked if it's resolved or not. I'll take your comment as granted.
I've re installed windows, so I'll check whether it is resolved or not later on when have time.

**Comment by inkthe0ry** [comment]
Hi, I'd like to report that it seems to not have been fixed, and I'm having this problem as well.

**Comment by wwboyer** [comment]
I'm having this same issue right now, it's definitely not fixed.

**Comment by adolfo-cia** [comment]
I have re opened the issue as other users reported that this is still not fixed.

**Comment by candestep** [comment]
I am having this issue right now, is there a fix for it?

**Comment by d1ffuser** [comment]
Out of nowhere I couldn't open/login the XBox accessories app. I thought it was because the XBox services weren't running, but what fixed it for me was resetting all XBox apps. 

Start > Installed Apps > XBox > "..." > Advanced > Reset

Uninstalling and reinstalling didn't work. Only resetting the apps fixed the issue. No need to run the XBox services, at least in my case. Hope this helps someone.

**Comment by StrixTyphoon** [comment]
Having this same issue which is stopping me from using an Instrument mapper to use my guitar hero controller with fortnite festival ([https://github.com/InvoxiPlayGames/FestivalInstrumentMapper/issues/64](url)) is there a fix yet or a way to undo the tweak that is causing this?

**Comment by candestep** [comment]
I got it to work now, but I had to re-download Windows through Windows Updates (System > Recovery > Fix problems using Windows Update). I didn't loose any of my personal files and data, but took a few hours. After this, XboxGivSvc was running again.

HOWEVER, that was not my issue actually. I couldn't see the Download button in the Xbox Accessories app in the Windows Store, which was due to my computer NOT having United States as it's country. After I changed from my country to United States in that configuration, the button appeared. Hopefully this helps someone else who might have the same issue.

**Comment by adolfo-cia** [comment]
Hello,
I tried the tool again and I can confirm that this issue still exsits.
Is there anyone that can help with troubleshooting?

thanks

**Comment by PRIME12602** [comment]
yeah its still an issue as its not working for me either, done almost everything but it just wont work!

**Comment by jacket430** [comment]
Hey, can confirm this is still an issue. After applying the standard set of tweaks XboxGipSvc just fails to start and hangs on "Starting".  This breaks the FortniteFestivalInstrumentMapper, as mentioned above. Undoing everything seems to fix it.

**Comment by jacket430** [comment]
Sorry for the double post, but this issue is still present and completely breaks XboxGipSvc, even with minimal tinkering. "Undoing" the options doesn't fix it, you have to go through a whole Windows restore to get it working again. candestep's steps worked for repairing it for me, but as it stands this tool, from what I can tell, is incompatible with anything relying on XboxGipSvc.

**Comment by franco6996** [comment]
I just have this bug where I want to connect my xbox controller to windows through the xbox wireless adapter, but when I press the sync button on the adapter the light doesn't blink, so the controller won't sync.
I think that it's related to this because I also have the service XboxGipSvc that don't start correctly.

**Comment by franco6996** [comment]
> I just have this bug where I want to connect my xbox controller to windows through the xbox wireless adapter, but when I press the sync button on the adapter the light doesn't blink, so the controller won't sync. I think that it's related to this because I also have the service XboxGipSvc that don't start correctly.

Ok, so I received the help of [novoide](https://github.com/novoide) and It now works!. I received the reply by email, but I dont see it here, so just in case someone needs it, here it goes his help:

> I fixed it after removing XboxGipSvc from regedit.
> `\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\XboxGipSvc\Parameters`
> 
> WARNING: DO NOT REMOVE xboxgipsvc.dll FROM SYSTEM32!!!!
> [image.png (view on web)](https://github.com/user-attachments/assets/89b9813e-efed-46f7-99de-5e371a97f205) 
>
> After that I rebooted and service disapeared as expected.
> Then I installed Xbox Gaming Services and I manually added XboxGipSvc into regedit via PowerShell:
> 
> `New-Item -Path "HKLM:\SYSTEM\CurrentControlSet\Services\XboxGipSvc" -Force Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\XboxGipSvc" -Name "Start" -Value 3 -Type DWord Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\XboxGipSvc" -Name "Type" -Value 16 -Type DWord Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\XboxGipSvc" -Name "ErrorControl" -Value 1 -Type DWord Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\XboxGipSvc" -Name "ImagePath" -Value "C:\Windows\system32\svchost.exe -k netsvcs -p" -Type String Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\XboxGipSvc" -Name "DisplayName" -Value "Xbox Accessory Management Service" -Type String Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\XboxGipSvc" -Name "ObjectName" -Value "LocalSystem" -Type String New-Item -Path "HKLM:\SYSTEM\CurrentControlSet\Services\XboxGipSvc\Parameters" -Force`
> 
> After this I added a parameter with dll location.
> [image.png (view on web)](https://github.com/user-attachments/assets/875c29e9-0b90-4005-a121-9d74a6363ecf)
> Reboot and Enjoy!
> [image.png (view on web)](https://github.com/user-attachments/assets/54c2ac41-63c9-4fc2-a165-5a833a2894d1)

After that last reboot, I needed to go to **Devices Manager** and unninstal the `XboxWireless Adapter for Windows`.
Un-plug and plug the xbox adapter and _voilà_!

**Comment by zyroeditzz** [comment]
Franco6996 after I did ur step why Type Value decimal is 16 isn't it supposed to be 32 and when I add another registry value Trigger info it won't even let me change the startup type
