### ISSUE TITLE
MicroWin - ISO Creation Error

### ISSUE THREAD

**Issue by adamshumpisxxx** [ChrisTitusTech/winutil#2179]
When trying to create a MicroWin ISO I get multiple errors related to not being able to remove OS packages as well as an Invoke-WPFMicrowin Line 3053 unexpected error (as seen below).

One could reproduce this error by trying to make a MicroWin ISO while unchecking all 4 "Keep" checkboxes. Both PowerShell 5 and 7 have the exact same issue.

Here is my $PSVersionTable readout:

```
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Here is the complete log of the process:

```

    CCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
 CCC::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
CC:::::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
C:::::CCCCCCCC::::CT:::::TT:::::::TT:::::TT:::::TT:::::::TT:::::T
C:::::C       CCCCCCTTTTTT  T:::::T  TTTTTTTTTTTT  T:::::T  TTTTTT
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C       CCCCCC        T:::::T                T:::::T
C:::::CCCCCCCC::::C      TT:::::::TT            TT:::::::TT
CC:::::::::::::::C       T:::::::::T            T:::::::::T
CCC::::::::::::C         T:::::::::T            T:::::::::T
  CCCCCCCCCCCCC          TTTTTTTTTTT            TTTTTTTTTTT

====Chris Titus Tech=====
=====Windows Toolbox=====
===========================================
---        Winget is installed          ---
===========================================
Version: v1.7.11261
    - Winget is a release version.
    - Winget is Up to Date

Winget is already installed.
No ISO is chosen+  C:\Scratch
Invoking WPFGetIso
         _                     __    __  _
  /\/\  (_)  ___  _ __   ___  / / /\ \ \(_) _ __
 /    \ | | / __|| '__| / _ \ \ \/  \/ /| || '_ \
/ /\/\ \| || (__ | |   | (_) | \  /\  / | || | | |
\/    \/|_| \___||_|    \___/   \/  \/  |_||_| |_|
oscdimg.exe on system: False
[INFO] oscdimg.exe SHA-256 Hash: AB9E161049D293B544961BFDF2D61244ADE79376D6423DF4F60BF9B147D3C78D
Hashes match. File is verified.
oscdimg.exe was successfully downloaded from github
File path C:\Users\Adam Shumpis\Downloads\Win11_23H2_English_x64v2.iso
You have enough space for this operation.
Mounting Iso. Please wait.
Done mounting Iso MSFT_DiskImage (ImagePath = "C:\Users\Adam Shumpis\Downloads\Win11_2..., StorageType = 1)
Iso mounted to 'E'
Setting up mount dir and scratch dirs
Mounting Iso. Please wait.
Done setting up mount dir and scratch dirs
Scratch dir is C:\Scratch\Scrach
Image dir is C:\Scratch\micro
Copying Windows image. This will take awhile, please don't use UI or cancel this step!
Copy 1031(s) from E: to C:\Scratch\micro
Copy complete! Total Time: 0m14s
Getting image information C:\Scratch\micro\sources\install.wim
Finding suitable Pro edition. This can take some time. Do note that this is an automatic process that might not select the edition you want.
Selected value '6 : Windows 11 Pro'.....
Done reading and unpacking ISO

*********************************
Check the UI for further steps!!!
Target ISO location: C:\Users\Adam Shumpis\Downloads\MicroWin11-06262024.iso
Index chosen: '6' from 6 : Windows 11 Pro
Mounting Windows image. This may take a while.
Mounting complete! Performing removal of applications...
Remove Features from the image
You can re-enable the disabled features at any time, using either Windows Update or the SxS folder in <installation media>\Sources.
Removing features complete!
Removing Appx Bloat
Could not remove OS package Microsoft-Windows-FodMetadata-Package~31bf3856ad364e35~amd64~~10.0.22621.1
Could not remove OS package Microsoft-Windows-Foundation-Package~31bf3856ad364e35~amd64~~10.0.22621.1
Could not remove OS package Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~en-US~11.0.22621.1
Could not remove OS package Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.2792
Could not remove OS package Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~wow64~~10.0.22621.2861
Could not remove OS package Microsoft-Windows-PowerShell-ISE-FOD-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-PowerShell-ISE-FOD-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-PowerShell-ISE-FOD-Package~31bf3856ad364e35~wow64~~10.0.22621.2861
Could not remove OS package Microsoft-Windows-Printing-PMCPPC-FoD-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-StepsRecorder-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-StepsRecorder-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-StepsRecorder-Package~31bf3856ad364e35~wow64~~10.0.22621.2861
Could not remove OS package Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~amd64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~wow64~en-US~10.0.22621.1
Could not remove OS package Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~wow64~~10.0.22621.2861
Could not remove OS package Package_for_DotNetRollup_481~31bf3856ad364e35~amd64~~10.0.9206.1
Could not remove OS package Package_for_KB5027397~31bf3856ad364e35~amd64~~22621.2355.1.1
Could not remove OS package Package_for_RollupFix~31bf3856ad364e35~amd64~~22621.2861.1.6
Invoke-WPFMicrowin:
Line |
3053 |          "WPFMicrowin" {Invoke-WPFMicrowin}
     |                         ~~~~~~~~~~~~~~~~~~
     | An unexpected error occurred: Removal failed. Please contact your software vendor.
Unmounting Registry...
Cleaning up image...
Cleanup complete.
Unmounting image...
Exporting image into C:\Scratch\micro\sources\install2.wim
Remove old 'C:\Scratch\micro\sources\install.wim' and rename C:\Scratch\micro\sources\install2.wim
Windows image completed. Continuing with boot.wim.
Mounting boot image C:\Scratch\micro\sources\boot.wim into C:\Scratch\Scrach
Loading registry...
Bypassing system requirements on the setup image
Unmounting Registry...
Unmounting image...
Creating ISO image
[INFO] Using oscdimg.exe from: C:\Users\ADAMSH~1\AppData\Local\Temp\oscdimg.exe
 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)


Performing Cleanup...
Done. ISO image is located here: C:\Users\Adam Shumpis\Downloads\MicroWin11-06262024.iso
```
I'll also add that there was another package attempting to be removed but the failure stopped it mid-flight and left a graphical glitch progress bar where it stopped even after everything stopped running. This conveys to me that the attempted removal of packages was cut short and more were to come. I didn't catch a screenshot of it but if truly required, I can.

**Comment by CodingWonders** [comment]
It should be fixed with PR #2192

**Comment by adamshumpisxxx** [comment]
I'll check and see if it works tomorrow and report back.

**Comment by adamshumpisxxx** [comment]
> It should be fixed with PR #2192

Still broken but in a slightly different way. I have since moved on to Windows 11 24H2 IoT Enterprise LTSC (26100.1.240331-1435.ge_release_CLIENT_ENTERPRISES_OEM_x64FRE_en-us.iso) and won't be tracking this anymore. I hope to see MicroWin sorted out in the future as it looks like a promising free stripped down alternative to NTLite.

```
    CCCCCCCCCCCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
 CCC::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
CC:::::::::::::::CT:::::::::::::::::::::TT:::::::::::::::::::::T
C:::::CCCCCCCC::::CT:::::TT:::::::TT:::::TT:::::TT:::::::TT:::::T
C:::::C       CCCCCCTTTTTT  T:::::T  TTTTTTTTTTTT  T:::::T  TTTTTT
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C                     T:::::T                T:::::T
C:::::C       CCCCCC        T:::::T                T:::::T
C:::::CCCCCCCC::::C      TT:::::::TT            TT:::::::TT
CC:::::::::::::::C       T:::::::::T            T:::::::::T
CCC::::::::::::C         T:::::::::T            T:::::::::T
  CCCCCCCCCCCCC          TTTTTTTTTTT            TTTTTTTTTTT

====Chris Titus Tech=====
=====Windows Toolbox=====
No ISO is chosen+  C:\Scratch
Invoking WPFGetIso
         _                     __    __  _
  /\/\  (_)  ___  _ __   ___  / / /\ \ \(_) _ __
 /    \ | | / __|| '__| / _ \ \ \/  \/ /| || '_ \
/ /\/\ \| || (__ | |   | (_) | \  /\  / | || | | |
\/    \/|_| \___||_|    \___/   \/  \/  |_||_| |_|
oscdimg.exe on system: False
[INFO] oscdimg.exe SHA-256 Hash: AB9E161049D293B544961BFDF2D61244ADE79376D6423DF4F60BF9B147D3C78D
Hashes match. File is verified.
oscdimg.exe was successfully downloaded from github
File path C:\Win11_23H2_English_x64v2.iso
You have enough space for this operation.
Mounting Iso. Please wait.
Done mounting Iso MSFT_DiskImage (ImagePath = "C:\Win11_23H2_English_x64v2.iso", StorageType = 1)
Iso mounted to 'E'
Setting up mount dir and scratch dirs
Mounting Iso. Please wait.
Done setting up mount dir and scratch dirs
Scratch dir is C:\Scratch\Scrach
Image dir is C:\Scratch\micro
Copying Windows image. This will take awhile, please don't use UI or cancel this step!
Copy 1031(s) from E: to C:\Scratch\micro
Copy complete! Total Time: 0m14s
Getting image information C:\Scratch\micro\sources\install.wim
Finding suitable Pro edition. This can take some time. Do note that this is an automatic process that might not select the edition you want.
Selected value '6 : Windows 11 Pro'.....
Done reading and unpacking ISO

*********************************
Check the UI for further steps!!!
Target ISO location: C:\MicroWin11_23H2_06302024.iso
Index chosen: '6' from 6 : Windows 11 Pro
Mounting Windows image. This may take a while.
Mounting complete! Performing removal of applications...
Remove Features from the image
You can re-enable the disabled features at any time, using either Windows Update or the SxS folder in <installation media>\Sources.
Removing features complete!
Removing Appx Bloat
Invoke-WPFMicrowin:
Line |
3117 |          "WPFMicrowin" {Invoke-WPFMicrowin}
     |                         ~~~~~~~~~~~~~~~~~~
     | An unexpected error occurred: The request is not supported.
Unmounting Registry...
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
ERROR: The parameter is incorrect.
Cleaning up image...
Cleanup complete.
Unmounting image...
Exporting image into C:\Scratch\micro\sources\install2.wim
Remove old 'C:\Scratch\micro\sources\install.wim' and rename C:\Scratch\micro\sources\install2.wim
Windows image completed. Continuing with boot.wim.
Mounting boot image C:\Scratch\micro\sources\boot.wim into C:\Scratch\Scrach
Loading registry...
Bypassing system requirements on the setup image
Unmounting Registry...
Unmounting image...
Creating ISO image
[INFO] Using oscdimg.exe from: C:\Users\ADAMSH~1\AppData\Local\Temp\oscdimg.exe
 _____
(____ \
 _   \ \ ___  ____   ____
| |   | / _ \|  _ \ / _  )
| |__/ / |_| | | | ( (/ /
|_____/ \___/|_| |_|\____)


Performing Cleanup...
Done. ISO image is located here: C:\MicroWin11_23H2_06302024.iso
```

**Comment by CodingWonders** [comment]
@adamshumpisxxx, that may not be related to AppX packages. The change proposed in #2251 will differentiate the OS package and app package removal processes.

I guess that package operations are failing.

**Comment by ctrlcmdshft** [comment]
Having same issue not creating ISO

**Comment by Orkunnnn** [comment]
Same problem. Any updates on that?

**Comment by ctrlcmdshft** [comment]
Ok so I did some testing the iso gets created fine, is you close out of microwin it then removes the iso

**Comment by adamshumpisxxx** [comment]
> Ok so I did some testing the iso gets created fine, is you close out of microwin it then removes the iso

I don't have the auto-deletion issue but I also can't verify if the ISO is "fine" given the way it stops it's operation stone cold dead when it hits the error it does. That would lead me to believe it kills the script before it does what it promises to do. I could be wrong.
