### ISSUE TITLE
'Customize Preferences' menu doesn't do anything

### ISSUE THREAD

**Issue by PluszDaniel** [ChrisTitusTech/winutil#3789]
### ⚙️ Issue Checklist

- [x] I have read the guidelines.
- [x] I checked for duplicate issues.
- [x] I searched for existing discussions.
- [x] I checked for an existing pull request that addresses this issue.

### 📜 What part of Winutil are you having issues with?

Tweaks

### 📝 Provide a clear and concise description of the issue.

I just installed Windows 11 25H2 on my pc, and I wanted to set the tweaks. The Essential and Advanced Tweaks are working fine, but the Preferences menu doesn't do anything

### 🔄 Steps to reproduce the issue.

Step 1: Open the tool.
Step 2: Click on Tweaks menu.
Step 3: Try enable/disable anything in the 'Customize Preferences' tab.

### 🖼️ Additional context.

https://github.com/user-attachments/assets/2d4fb646-04ec-4083-b9b4-e115d0553039

**Comment by issacs-tech** [comment]
Exactly same issue installed today 25H2 (Microwin) on brand new laptop and customize preferences does NOTHING! 
this is new issue !

Thanks Issac

**Comment by ghost** [comment]
launch the dev version
```powershell
irm christitus.com/windev | iex
```

**Comment by issacs-tech** [comment]
Wow OK Thanks

**Comment by dave-mike** [comment]
> launch the dev version
> 
> irm christitus.com/windev | iex

Same issue on Win 11 Pro 24H2 even with the dev version

**Comment by ghost** [comment]
> > launch the dev version
> > irm christitus.com/windev | iex
> 
> Same issue on Win 11 Pro 24H2 even with the dev version

dev version should work can you send a video?

**Comment by dave-mike** [comment]
> > > launch the dev version
> > > irm christitus.com/windev | iex
> > 
> > 
> > Same issue on Win 11 Pro 24H2 even with the dev version
> 
> dev version should work can you send a video?

Seems when I start an unpriviledged power shell and try to use the script (after it asks for elevation) that section doesn't work but when I start a power shell directly as admin it works 

I'm guessing it's unrelated to this thread, just a lucky coincidence

**Comment by BobbyESP** [comment]
Confirmed on version 25H2.

It's important to note that **auto-elevation is not sufficient** to solve the issue. The switches only become enabled and function properly when the terminal is explicitly run as an administrator (Run as Administrator).

**Comment by ghost** [comment]
> Confirmed on version 25H2.
> 
> It's important to note that **auto-elevation is not sufficient** to solve the issue. The switches only become enabled and function properly when the terminal is explicitly run as an administrator (Run as Administrator).

this issue is solved just run the dev version

**Comment by BobbyESP** [comment]
Well for me it is still happening even in dev version... (using Terminal application for executing the commands)

> > Confirmed on version 25H2.
> > It's important to note that **auto-elevation is not sufficient** to solve the issue. The switches only become enabled and function properly when the terminal is explicitly run as an administrator (Run as Administrator).
> 
> this issue is solved just run the dev version

**Comment by ghost** [comment]
> Well for me it is still happening even in dev version... (using Terminal application for executing the commands)
> 
> > > Confirmed on version 25H2.
> > > It's important to note that **auto-elevation is not sufficient** to solve the issue. The switches only become enabled and function properly when the terminal is explicitly run as an administrator (Run as Administrator).
> > 
> > 
> > this issue is solved just run the dev version

so you open powershell as admin run `irm christitus.com/windev | iex` and when you click the toggle switches it dosen't say anything in the powershell window?

**Comment by BobbyESP** [comment]
> > Well for me it is still happening even in dev version... (using Terminal application for executing the commands)
> > > > Confirmed on version 25H2.
> > > > It's important to note that **auto-elevation is not sufficient** to solve the issue. The switches only become enabled and function properly when the terminal is explicitly run as an administrator (Run as Administrator).
> > > 
> > > 
> > > this issue is solved just run the dev version
> 
> so you open powershell as admin run `irm christitus.com/windev | iex` and when you click the toggle switches it dosen't say anything in the powershell window?

No. That makes the program work perfectly, as I mentioned. The problem arises when you start the terminal without admin privileges. The program attempts to launch another terminal as admin, but this new window lacks permissions, or at least the switches do nothing.

**Comment by ghost** [comment]
than just run it as admin

**Comment by jimlosengewrapper-alt** [comment]
try and customize these settings within regedit, that usually helps to eliminate the gui frontend glitching out.

**Comment by ghost** [comment]
fixes now /close
