### ISSUE TITLE
Cannot install edge

### ISSUE THREAD

**Issue by Arindam905** [ChrisTitusTech/winutil#681]
I removed ms edge using your tool sir but now I want to install it again so I did undo tweak it didn't work and if i download it manually also it dose not install......can't I use edge again?

**Comment by kntndrsn** [comment]
Solved in #340 
See [https://github.com/ChrisTitusTech/winutil/issues/340#issuecomment-1450087676](url)

**Comment by Arindam905** [comment]
> Solved in #340 

Those didn't work I mean I the actual edge icon still can't open edge I have use the msedge.exe to open edge.... :_)

**Comment by Arindam905** [comment]
> Solved in #340 

Thank yoy
