### ISSUE TITLE
Winget script 

### ISSUE THREAD

**Issue by YusufKhalifa1** [ChrisTitusTech/winutil#943]
**Is your feature request related to a problem? Please describe.**
yes, the winget script doesn't work anymore at least for my case (windows 10).

**Describe the solution you'd like**
change the script that installs winget in the winutil if not installed to a better one.

**Describe alternatives you've considered**
I found a script that worked pretty well for me and for others ( windows10,11,10server)
here is the script : https://raw.githubusercontent.com/asheroto/winget-install/master/winget-install.ps1

# comment
you should change it to this and try it yourself first

**Comment by ChrisTitusTech** [comment]
Fixed in commit 8e138c3

**Comment by CaptainV0408** [comment]
Still a problem in the latest main branch running Windows 10 IoT Enterprise LTSC 19044.3324
![Winget failed Install](https://github.com/ChrisTitusTech/winutil/assets/141863162/01e0c842-66ab-4132-bf21-6b58e205affb)
Setup by Admin Powershell: 
```powershell
irm https://christitus.com/win | iex
```
